server:
  port: 18092
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1
  thymeleaf:
    cache: false
  redis:
    host: 192.168.93.128
  rabbitmq:
    virtual-host: /ruinan
    host: 192.168.93.128
    username: ruinan
    password: ruinan
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: manual
feign:
  sentinel:
    enabled: true
threadPool:
  coreSize: 100
  maxSize: 500
  keepAlive: 60
  blockingSize: 10000
