server:
  port: 8888
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: pms-route # 商品管理路由
          uri: lb://pms-service
          predicates:
            - Path=/pms/**
        - id: oms-route # 订单管理路由
          uri: lb://oms-service
          predicates:
            - Path=/oms/**
        - id: ums-route # 用户管理路由
          uri: lb://ums-service
          predicates:
            - Path=/ums/**
        - id: wms-route # 仓库管理路由
          uri: lb://wms-service
          predicates:
            - Path=/wms/**
        - id: sms-route # 营销管理路由
          uri: lb://sms-service
          predicates:
            - Path=/sms/**
        - id: search-route #搜索路由
          uri: lb://search-service
          predicates:
            - Host=search.gmall.com
        - id: index-route1 # 首页的异步请求路由
          uri: lb://index-service
          predicates:
            - Path=/index/**
        - id: index-route2 #  域名映射的路由 (需要以域名访问)
          uri: lb://index-service
          predicates:
            - Host=gmall.com,www.gmall.com
        - id: item-route #  商品详情页的异步请求路由
          uri: lb://item-service
          predicates:
            - Host=item.gmall.com
        - id: auth-route #  单点登录请求路由
          uri: lb://auth-service
          predicates:
            - Host=sso.gmall.com
        - id: cart-route #  单点登录请求路由
          uri: lb://cart-service
          predicates:
            - Host=cart.gmall.com
        - id: order-route #  订单请求路由
          uri: lb://order-service
          predicates:
            - Host=order.gmall.com
          filters:
            - Auth=/
jwt:
  pubKeyPath: D:\MyWork\project-0522\rsa\rsa.pub
  cookieName: GMALL-TOKEN